#!/bin/bash

# Helper script to display environment variables for Vercel deployment

echo "================================================"
echo "  VERCEL ENVIRONMENT VARIABLES"
echo "================================================"
echo ""
echo "Copy these values to Vercel when deploying:"
echo ""
echo "1. NEXT_PUBLIC_SUPABASE_URL"
echo "   Value: $(grep NEXT_PUBLIC_SUPABASE_URL .env.local | cut -d '=' -f2-)"
echo ""
echo "2. NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   Value: $(grep NEXT_PUBLIC_SUPABASE_ANON_KEY .env.local | cut -d '=' -f2-)"
echo ""
echo "3. NEXT_PUBLIC_SITE_URL"
echo "   Value: (leave empty for first deployment, update after)"
echo ""
echo "================================================"
echo "  OPTIONAL - API KEYS"
echo "================================================"
echo ""
echo "4. NEXT_PUBLIC_API_URL (optional)"
echo "   Value: $(grep NEXT_PUBLIC_API_URL .env.production | cut -d '=' -f2-)"
echo ""
echo "5. NEXT_PUBLIC_GEMINI_API_KEY (optional)"
echo "   Value: $(grep NEXT_PUBLIC_GEMINI_API_KEY .env.production | cut -d '=' -f2-)"
echo ""
echo "================================================"
echo "Note: Make sure to enable all 3 environments"
echo "      (Production, Preview, Development)"
echo "================================================"
